baseurl: https://dkac97.corp.lego.com:22030/sap(bD1lbiZjPTQxMSZkPW1pbg==)/bc/bsp/sap/crm_ui_start/default.htm



d11:
  website: https://dkac97.corp.lego.com:22030/sap(bD1lbiZjPTQxMSZkPW1pbg==)/bc/bsp/sap/crm_ui_start/default.htm
q11:
  website: https://dkasq11c00.corp.lego.com:22032/sap(bD1lbiZjPTMxMSZkPW1pbg==)/bc/bsp/sap/crm_ui_start/default.htm
z11:
  website: https://dkaviz.corp.lego.com:22063/sap(bD1lbiZjPTQxMSZkPW1pbg==)/bc/bsp/sap/crm_ui_start/default.htm
p11:
  website: https://dkac97.corp.lego.com:22030/sap(bD1lbiZjPTQxMSZkPW1pbg==)/bc/bsp/sap/crm_ui_start/default.htm
